### ISSUE TITLE
PersonFS Failed Connection

### ISSUE THREAD

**Issue by avma** [jmichault/gramps-kromprogramoj#24]
A popup dialog shows after typing in password in the FS Gramplet tab saying that the connection failed and FS features will not be available for use. This is happening on every attempt of using the Granplt.

This was perfectly working until a bout a month ago, no changes have been made to the Gramps environment during that month (haven't even logged-in to Gramps).

Completely removing (deleting the add-on folder) and adding the Gramplet back (following the install instructions) did not fix the issue.

I submitted a bug report to Gamps but it was declined with the following replay:
`Closing as not an addon supported by Gramps projects @ https://github.com/gramps-project/addons-source Please contact the developer of this addon directly at https://github.com/jmichault/PersonFS/issues`

**Comment by jmichault** [comment]
It appears that Familysearch added an anti-bot detector.

getmyancestors is facing the same problem : 
[issue 54](https://github.com/Linekio/getmyancestors/issues/54)
[issue 55](https://github.com/Linekio/getmyancestors/issues/55)

Actually, the only solution is to obtain a valid client_id, but  FamilySearch refuses to provide it to open source developers.

If you find a client_id, you can add a line like this in PersonFS.ini : 
`fs_client_id='xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx'`

**Comment by avma** [comment]
From what I understand they need to grant credentials to the application firs...

[https://www.familysearch.org/developers/docs/guides/authentication#client-credentials](url)
`Client Credentials

Client credentials authentication can be granted to your app independent of the users who are using it. This is not available for general use. To obtain client credential authentication, you must first contact devsupport@familysearch.org to obtain special permission and assignment.`

**Comment by edcrfv0** [comment]
> If you find a client_id, you can add a line like this in PersonFS.ini : `fs_client_id='xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx'`

Could you actually make that work? I tried with a few existing `client_id`s found in some officially supported apps https://grms.my.site.com/solutionsgallery/ but none worked 😕

**Comment by jmichault** [comment]
the 2.0.37 release for gramps 5.2 should resolve this issue.
